[package]
name = "key-value-store"
version = "0.1.0"
edition = "2024"

[lib]
name = "key_value_store"
path = "src/lib.rs"

[workspace]
members = ["bench"]

[dependencies]
postcard = { version = "1.1.3", features = ["alloc"] }
serde = "1.0.228"
rand = "0.9.2"
log = "0.4.29"
